config/routes.rb
Rails.application.routes.draw do
  root 'open_jtalk#index'
  get 'index' => 'open_jtalk#index'
  get 'synthesis' => 'open_jtalk#synthesis'
  post 'synthesis' => 'open_jtalk#synthesis'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/open_jtalk_controller.rb
require 'lame'
require 'open_jtalk'

class OpenJtalkController < ApplicationController
  rescue_from ActionController::ParameterMissing do
    render nothing: true, status: :bad_request
  end

  def index
  end

  def synthesis
    text = param_text
    config = param_config

    response.headers['Content-Type'] = 'audio/mp3'
    self.response_body = OpenJtalk::Mp3StreamingSynthesizer.new(config, text)
  end

  private

  def param_text
    fail ActionController::ParameterMissing, :text if params.blank?

    text = params[:text]
    fail ActionController::ParameterMissing, :text if text.nil?
    text
  end

  def param_config
    style = params[:style] || "Mei::NORMAL"
    config = begin
      "OpenJtalk::Config::#{style}".constantize
    rescue
      nil
    end
    fail ActionController::ParameterMissing, :style unless config
    config
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Open JTalk Server</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body class="container">
  <div class="row">
    <div class="span12">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/open_jtalk/index.html.erb
<div class="row">
  <div class="span12">
    <%= form_tag synthesis_path, :method => 'get' do %>
      <fieldset>
        <legend>Open JTalk</legend>
        <%= text_area_tag :text, params[:text], :placeholder => "Type something…", :rows => 10, :style => "width: 100%;" %>
        <select name="style">
          <option>Mei::NORMAL</option>
          <option>Mei::ANGRY</option>
          <option>Mei::BASHFUL</option>
          <option>Mei::HAPPY</option>
          <option>Mei::SAD</option>
          <option>Mei::FAST</option>
          <option>Mei::SLOW</option>
          <option>Mei::HIGH</option>
          <option>Mei::LOW</option>
          <option>Nitech::NORMAL</option>
          <option>Nitech::FAST</option>
          <option>Nitech::SLOW</option>
          <option>Nitech::HIGH</option>
          <option>Nitech::LOW</option>
        </select>
        <%= submit_tag I18n.t("synthesis"), :class => "btn" %>
      </fieldset>
    <% end %>
  </div>
</div>